license="${license}"
issueTrackerURL="${issue_tracker}"

[[mods]]
modId="blazerod_render"
version="${version}"
displayName="BlazeRod render"
displayURL="${home_page}"
logoFile="assets/blazerod/icon.png"
authors="fifth_light"
description='''Render part of BlazeRod. Render your model into Minecraft.'''

[[mixins]]
config="blazerod.mixins.json"

[[accessTransformers]]
file="access_transformer.cfg"

[[dependencies.blazerod_render]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="CLIENT"

[[dependencies.blazerod_render]]
modId="minecraft"
type="required"
versionRange="${game_version}"
ordering="NONE"
side="CLIENT"

[[dependencies.blazerod_render]]
modId="kotlinforforge"
type="required"
ordering="NONE"
side="CLIENT"

[[dependencies.blazerod_render]]
modId="blazerod_model_base"
type="required"
ordering="NONE"
side="CLIENT"
