[book]
authors = ["WhiteElephant-abc", "fifth_light", "fengzhou0w0"]
title = "TouchControllerWiki"
language = "cmn-hans-cn"

[output.html]
git-repository-url = "https://github.com/TouchController/TouchController-Monorepo/tree/master/touchcontroller/wiki"
additional-js = ["custom.js"]
