license="${license}"
issueTrackerURL="${issue_tracker}"

[[mods]]
modId="armorstand"
version="${version}"
displayName="ArmorStand"
displayURL="${home_page}"
logoFile="assets/armorstand/icon.png"
authors="fifth_light"
description='''Load your models into Minecraft!'''

[[mixins]]
config="armorstand.mixins.client.json"

[[accessTransformers]]
file="access_transformer.cfg"

[[dependencies.armorstand]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="CLIENT"

[[dependencies.armorstand]]
modId="minecraft"
type="required"
versionRange="${game_version}"
ordering="NONE"
side="CLIENT"

[[dependencies.armorstand]]
modId="kotlinforforge"
type="required"
ordering="NONE"
side="CLIENT"

[[dependencies.armorstand]]
modId="blazerod_model_base"
type="required"
ordering="NONE"
side="CLIENT"

[[dependencies.armorstand]]
modId="blazerod_model_formats"
type="required"
ordering="NONE"
side="CLIENT"
