name: Build ArmorStand and BlazeRod
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r28b
      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.14.0
      - name: Build
        run: |
          bazel build \
            --verbose_failures \
            //armorstand:mod_fabric \
            //armorstand:mod_neoforge \
            //blazerod:blazerod_fabric \
            //blazerod:blazerod_neoforge \
            //blazerod/model/model-base \
            //blazerod/model/model-formats \
            //blazerod/model/model-gltf \
            //blazerod/model/model-pmd \
            //blazerod/model/model-pmx \
            //blazerod/model/model-vmd \
            //blazerod/model/model-assimp:model-assimp-merged \
            //blazerod/example/ball_block
      - name: Test
        run: |
          bazel test \
            --verbose_failures \
            //blazerod/model:test \
            //blazerod/render:test
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-bazel
          path: |
            bazel-bin/armorstand/mod_fabric.jar
            bazel-bin/armorstand/mod_neoforge.jar
            bazel-bin/blazerod/blazerod_fabric.jar
            bazel-bin/blazerod/blazerod_neoforge.jar
            bazel-bin/blazerod/model/model-base/model-base.jar
            bazel-bin/blazerod/model/model-formats/model-formats.jar
            bazel-bin/blazerod/model/model-gltf/model-gltf.jar
            bazel-bin/blazerod/model/model-pmd/model-pmd.jar
            bazel-bin/blazerod/model/model-pmx/model-pmx.jar
            bazel-bin/blazerod/model/model-vmd/model-vmd.jar
            bazel-bin/blazerod/model/model-assimp/model-assimp-merged.jar
            bazel-bin/blazerod/example/ball_block/ball_block.jar
